export enum GamepadBind {
    Up = 0,
    Down = 1,
    Left = 2,
    Right = 3,
    LeftBumper = 4,
    LeftTrigger = 5,
    RightBumper = 6,
    RightTrigger = 7,
    RightTriggerFull = 8,
    LeftTriggerFull = 9,
    Select = 10,
    Start = 11,
    Home = 12,
    Capture = 13,
    LeftPaddleLeft = 14,
    RightPaddleLeft = 15,
    LeftPaddleRight = 16,
    RightPaddleRight = 17,
    LeftStickClick = 18,
    RightStickClick = 19,
    North = 20,
    East = 21,
    South = 22,
    West = 23,
    LeftStickUp = 24,
    LeftStickDown = 25,
    LeftStickLeft = 26,
    LeftStickRight = 27,
    LeftStickRing = 28,
    RightStickUp = 29,
    RightStickDown = 30,
    RightStickLeft = 31,
    RightStickRight = 32,
    RightStickRing = 33,
    MotionStickUp = 34,
    MotionStickDown = 35,
    MotionStickLeft = 36,
    MotionStickRight = 37,
    MotionStickRing = 38,
    LeanLeft = 39,
    LeanRight = 40,
    Touch = 41,
    NoInput = 42,
}

export const gamepadBindToJsmString = new Map<GamepadBind, string>([
    [GamepadBind.Up, 'UP'],
    [GamepadBind.Down, 'DOWN'],
    [GamepadBind.Left, 'LEFT'],
    [GamepadBind.Right, 'RIGHT'],
    [GamepadBind.LeftBumper, 'L'],
    [GamepadBind.LeftTrigger, 'ZL'],
    [GamepadBind.RightBumper, 'R'],
    [GamepadBind.RightTrigger, 'ZR'],
    [GamepadBind.RightTriggerFull, 'ZRF'],
    [GamepadBind.LeftTriggerFull, 'ZLF'],
    [GamepadBind.Select, '-'],
    [GamepadBind.Start, '+'],
    [GamepadBind.Home, 'HOME'],
    [GamepadBind.Capture, 'CAPTURE'],
    [GamepadBind.LeftPaddleLeft, 'LSL'],
    [GamepadBind.RightPaddleLeft, 'RSL'],
    [GamepadBind.LeftPaddleRight, 'LSR'],
    [GamepadBind.RightPaddleRight, 'RSR'],
    [GamepadBind.LeftStickClick, 'L3'],
    [GamepadBind.RightStickClick, 'R3'],
    [GamepadBind.North, 'N'],
    [GamepadBind.East, 'E'],
    [GamepadBind.South, 'S'],
    [GamepadBind.West, 'W'],
    [GamepadBind.LeftStickUp, 'LUP'],
    [GamepadBind.LeftStickDown, 'LDOWN'],
    [GamepadBind.LeftStickLeft, 'LLEFT'],
    [GamepadBind.LeftStickRight, 'LRIGHT'],
    [GamepadBind.LeftStickRing, 'LRING'],
    [GamepadBind.RightStickUp, 'RUP'],
    [GamepadBind.RightStickDown, 'RDOWN'],
    [GamepadBind.RightStickLeft, 'RLEFT'],
    [GamepadBind.RightStickRight, 'RRIGHT'],
    [GamepadBind.RightStickRing, 'RRING'],
    [GamepadBind.MotionStickUp, 'MUP'],
    [GamepadBind.MotionStickDown, 'MDOWN'],
    [GamepadBind.MotionStickLeft, 'MLEFT'],
    [GamepadBind.MotionStickRight, 'MRIGHT'],
    [GamepadBind.MotionStickRing, 'MRING'],
    [GamepadBind.LeanLeft, 'LEAN_LEFT'],
    [GamepadBind.LeanRight, 'LEAN_RIGHT'],
    [GamepadBind.Touch, 'TOUCH'],
    [GamepadBind.NoInput, 'NONE'],
]);

export const jsmStringToGamepadBind = new Map<string, GamepadBind>([
    ['UP', GamepadBind.Up],
    ['DOWN', GamepadBind.Down],
    ['LEFT', GamepadBind.Left],
    ['RIGHT', GamepadBind.Right],
    ['L', GamepadBind.LeftBumper],
    ['ZL', GamepadBind.LeftTrigger],
    ['R', GamepadBind.RightBumper],
    ['ZR', GamepadBind.RightTrigger],
    ['ZRF', GamepadBind.RightTriggerFull],
    ['ZLF', GamepadBind.LeftTriggerFull],
    ['-', GamepadBind.Select],
    ['+', GamepadBind.Start],
    ['HOME', GamepadBind.Home],
    ['CAPTURE', GamepadBind.Capture],
    ['LSL', GamepadBind.LeftPaddleLeft],
    ['RSL', GamepadBind.RightPaddleLeft],
    ['LSR', GamepadBind.LeftPaddleRight],
    ['RSR', GamepadBind.RightPaddleRight],
    ['L3', GamepadBind.LeftStickClick],
    ['R3', GamepadBind.RightStickClick],
    ['N', GamepadBind.North],
    ['E', GamepadBind.East],
    ['S', GamepadBind.South],
    ['W', GamepadBind.West],
    ['LUP', GamepadBind.LeftStickUp],
    ['LDOWN', GamepadBind.LeftStickDown],
    ['LLEFT', GamepadBind.LeftStickLeft],
    ['LRIGHT', GamepadBind.LeftStickRight],
    ['LRING', GamepadBind.LeftStickRing],
    ['RUP', GamepadBind.RightStickUp],
    ['RDOWN', GamepadBind.RightStickDown],
    ['RLEFT', GamepadBind.RightStickLeft],
    ['RRIGHT', GamepadBind.RightStickRight],
    ['RRING', GamepadBind.RightStickRing],
    ['MUP', GamepadBind.MotionStickUp],
    ['MDOWN', GamepadBind.MotionStickDown],
    ['MLEFT', GamepadBind.MotionStickLeft],
    ['MRIGHT', GamepadBind.MotionStickRight],
    ['MRING', GamepadBind.MotionStickRing],
    ['LEAN_LEFT', GamepadBind.LeanLeft],
    ['LEAN_RIGHT', GamepadBind.LeanRight],
    ['TOUCH', GamepadBind.Touch],
    ['NONE', GamepadBind.NoInput],
]);