export enum GamePadBind {
    Up = 0,
    Down = 1,
    Left = 2,
    Right = 3,
    LeftBumper = 4,
    LeftTrigger = 5,
    RightBumper = 6,
    RightTrigger = 7,
    RightTriggerFull = 8,
    LeftTriggerFull = 9,
    Select = 10,
    Start = 11,
    Home = 12,
    Capture = 13,
    LeftPaddleLeft = 14,
    RightPaddleLeft = 15,
    LeftPaddleRight = 16,
    RightPaddleRight = 17,
    LeftStickClick = 18,
    RightStickClick = 19,
    North = 20,
    East = 21,
    South = 22,
    West = 23,
    LeftStickUp = 24,
    LeftStickDown = 25,
    LeftStickLeft = 26,
    LeftStickRight = 27,
    LeftStickRing = 28,
    RightStickUp = 29,
    RightStickDown = 30,
    RightStickLeft = 31,
    RightStickRight = 32,
    RightStickRing = 33,
    MotionStickUp = 34,
    MotionStickDown = 35,
    MotionStickLeft = 36,
    MotionStickRight = 37,
    MotionStickRing = 38,
    LeanLeft = 39,
    LeanRight = 40,
    Touch = 41,
    NoInput = 42,
}

export const gamepadBindToJsmString = new Map<GamePadBind, string>([
    [GamePadBind.Up, 'UP'],
    [GamePadBind.Down, 'DOWN'],
    [GamePadBind.Left, 'LEFT'],
    [GamePadBind.Right, 'RIGHT'],
    [GamePadBind.LeftBumper, 'L'],
    [GamePadBind.LeftTrigger, 'ZL'],
    [GamePadBind.RightBumper, 'R'],
    [GamePadBind.RightTrigger, 'ZR'],
    [GamePadBind.RightTriggerFull, 'ZRF'],
    [GamePadBind.LeftTriggerFull, 'ZLF'],
    [GamePadBind.Select, '-'],
    [GamePadBind.Start, '+'],
    [GamePadBind.Home, 'HOME'],
    [GamePadBind.Capture, 'CAPTURE'],
    [GamePadBind.LeftPaddleLeft, 'LSL'],
    [GamePadBind.RightPaddleLeft, 'RSL'],
    [GamePadBind.LeftPaddleRight, 'LSR'],
    [GamePadBind.RightPaddleRight, 'RSR'],
    [GamePadBind.LeftStickClick, 'L3'],
    [GamePadBind.RightStickClick, 'R3'],
    [GamePadBind.North, 'N'],
    [GamePadBind.East, 'E'],
    [GamePadBind.South, 'S'],
    [GamePadBind.West, 'W'],
    [GamePadBind.LeftStickUp, 'LUP'],
    [GamePadBind.LeftStickDown, 'LDOWN'],
    [GamePadBind.LeftStickLeft, 'LLEFT'],
    [GamePadBind.LeftStickRight, 'LRIGHT'],
    [GamePadBind.LeftStickRing, 'LRING'],
    [GamePadBind.RightStickUp, 'RUP'],
    [GamePadBind.RightStickDown, 'RDOWN'],
    [GamePadBind.RightStickLeft, 'RLEFT'],
    [GamePadBind.RightStickRight, 'RRIGHT'],
    [GamePadBind.RightStickRing, 'RRING'],
    [GamePadBind.MotionStickUp, 'MUP'],
    [GamePadBind.MotionStickDown, 'MDOWN'],
    [GamePadBind.MotionStickLeft, 'MLEFT'],
    [GamePadBind.MotionStickRight, 'MRIGHT'],
    [GamePadBind.MotionStickRing, 'MRING'],
    [GamePadBind.LeanLeft, 'LEAN_LEFT'],
    [GamePadBind.LeanRight, 'LEAN_RIGHT'],
    [GamePadBind.Touch, 'TOUCH'],
    [GamePadBind.NoInput, 'NONE'],
]);

export const jsmStringToGamepadBind = new Map<string, GamePadBind>([
    ['UP', GamePadBind.Up],
    ['DOWN', GamePadBind.Down],
    ['LEFT', GamePadBind.Left],
    ['RIGHT', GamePadBind.Right],
    ['L', GamePadBind.LeftBumper],
    ['ZL', GamePadBind.LeftTrigger],
    ['R', GamePadBind.RightBumper],
    ['ZR', GamePadBind.RightTrigger],
    ['ZRF', GamePadBind.RightTriggerFull],
    ['ZLF', GamePadBind.LeftTriggerFull],
    ['-', GamePadBind.Select],
    ['+', GamePadBind.Start],
    ['HOME', GamePadBind.Home],
    ['CAPTURE', GamePadBind.Capture],
    ['LSL', GamePadBind.LeftPaddleLeft],
    ['RSL', GamePadBind.RightPaddleLeft],
    ['LSR', GamePadBind.LeftPaddleRight],
    ['RSR', GamePadBind.RightPaddleRight],
    ['L3', GamePadBind.LeftStickClick],
    ['R3', GamePadBind.RightStickClick],
    ['N', GamePadBind.North],
    ['E', GamePadBind.East],
    ['S', GamePadBind.South],
    ['W', GamePadBind.West],
    ['LUP', GamePadBind.LeftStickUp],
    ['LDOWN', GamePadBind.LeftStickDown],
    ['LLEFT', GamePadBind.LeftStickLeft],
    ['LRIGHT', GamePadBind.LeftStickRight],
    ['LRING', GamePadBind.LeftStickRing],
    ['RUP', GamePadBind.RightStickUp],
    ['RDOWN', GamePadBind.RightStickDown],
    ['RLEFT', GamePadBind.RightStickLeft],
    ['RRIGHT', GamePadBind.RightStickRight],
    ['RRING', GamePadBind.RightStickRing],
    ['MUP', GamePadBind.MotionStickUp],
    ['MDOWN', GamePadBind.MotionStickDown],
    ['MLEFT', GamePadBind.MotionStickLeft],
    ['MRIGHT', GamePadBind.MotionStickRight],
    ['MRING', GamePadBind.MotionStickRing],
    ['LEAN_LEFT', GamePadBind.LeanLeft],
    ['LEAN_RIGHT', GamePadBind.LeanRight],
    ['TOUCH', GamePadBind.Touch],
    ['NONE', GamePadBind.NoInput],
]);